name: lifecycler
publish_to: none
description: Local module.

version: 0.0.0+0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter
